### PR TITLE
Styleguide

### PR DESCRIPTION
**Pull request by xavierfoucrier**
Upgrades the **code style guide** to fit most open source project conventions on Github, allowing better code display and git diff. Need to discuss a little before apply and merge.

### CODE REVIEW

**Comment by peterennis** [comment]
I use VS Code.
It would be nice to have some standard set-it-and-forget-it configuration.

**Comment by xavierfoucrier** [comment]
I work on Atom, and like Visual Studio Code, you need to download a package to suppor the .editorconfig file notation. Can you try and give a feedback about this configuration? We should merge this PR quickly before doing core code modifications.

**Comment by peterennis** [comment]
Compare with this one:

capture483

**Comment by xavierfoucrier** [comment]
Perfect, sounds good!

Remove the final newline on markdown files doesn't really make sense and doesn't matter.
I will merge the PR today. :tada:

**Pull request merged**
