### PR TITLE
MOJS2 (test) - fix deps to resolve security issues, build and verify tests

### PR DESCRIPTION
**Pull request by peterennis**
No more security complaints from npm audit

### CODE REVIEW

**Comment by peterennis** [comment]
capture489

**Comment by peterennis** [comment]
The branch now builds with one warning:

capture490

**Comment by peterennis** [comment]
`npm test` returns TOTAL: 107 SUCCESS

capture491

**Comment by peterennis** [comment]
`npm run-script test-dev` returns TOTAL: 1 FAILED, 106 SUCCESS

capture492

**Comment by peterennis** [comment]
`npm run-script analyze` returns "webpack is watching the files"

capture493

**Comment by peterennis** [comment]
@xavierfoucrier, @Sandstedt 

I do not have sufficient knowledge of the code and development process to take
this much further without a lot of study.

Pointers appreciated for next steps e.g.

1. Debug the error
2. Run some demos
3. Process documentation
4. Onboarding/contrib docs for other developers
5. Code review standards
6. Prettier/Eslint/Others...
7. Babel 7 and Babel-loader 8 : Pros/Cons, Timeline
8. Are old bugs solved in the new version? Update tickets as needed
9. Upgrade other projects if they have a v2 branch (I can look into this next)
10. Start a vNext planning doc ???

:smile:

**Comment by Sandstedt** [comment]
I think fixing the test eror can be a separate task. Its best to just merge in the secutity fixes first. Or did you see this eror before you fixed the security updates? Eg was it an old error?

**Comment by Sandstedt** [comment]
And a small thing. Should it be mojs or mo · js (mo.jsj)? Its a motion library. Build with JS, not Mojs as a name right?

**Comment by peterennis** [comment]
@xavierfoucrier, @Sandstedt I do not know if this was an old error, but I am really impressed there is only one!

Re: mojs/mo.js etc.
I do not feel inclined to support spammers misusing the legacy name.
I will instead use MOFTW in the dev code as a place holder for
some alternative.
It will be easier for future search and replace, TBD.

**Comment by xavierfoucrier** [comment]
@Sandstedt @peterennis It's definitely `mo.js` to avoid confusion with the old NPM package, but use `mojs` keyword when you talk about the library :wink: 

@peterennis nice work with this PR! Be sure to **use Slack for discussion** and open threads into channels to talk about specific things like https://github.com/mojs-contrib/mojs/pull/9#issuecomment-462105591 :+1:

**Pull request merged**
